### ISSUE TITLE
Slides display and position suggestion

### ISSUE THREAD

**Issue by GiuTaeKim** [meandmax/lory#133]
Hello. I rly appreciate the work you are doing for developing good-quality vanilla extensions.

I like lory features. But the only thing that makes me step back to using on my projects is related about how the slides are positioned and the default css styles.

__It's well known that inline-block is suposed to not be used for grid-like design__ (Google it). As is not floated, the browser show it like normal text and also show ugly spaces between them. Ok... you fix it setting font-size:0 and line-height:0.

But this brings a little __problem with relative font-sizes__ in responsive design. I mean when using font sizes according to parent font size: using the em unit. If I use em units to set the content of slides: the content dissappear. Of course... because set a font size according to 0 will gives 0.

Yeah... I know... I can set the font-size using px manually, but in that way I must set the correct font-size for each item inside slides in each media query... using em units will become pointless, and for a lot of people em unit are very very useful. Of course... this will make the css bigger also...

In other hand... __setting font-size:0 and line-height:0 seems like some kind of content hiding that may cause SEO penalties__. I´m not shure about this... but I would't risk myself to let some bots think that I wanna hide valuable content. And the way bots analize sites changes constantly.

Anyway... Regardless of the points mentioned above... it simply feels like a poor and ugly hack to makes it work.

I suggest using display:block and floating instead. Or maybe, the new display:flexbox and display:grid and makes a fallback.

I hope you have understood me. Sorry for the criticism and also for my bad english. Keep the good work.

**Comment by meandmax** [comment]
Hey @GiuTaeKim,

I really do not give you any specifications on how to structure your css to get it up and running. Yeah I could imagine that lory has more examples with different layout variants, so feel free to either contribute.

If u can use other css models that work better for you, just use it. My CSS is actually just for demo purposes.

In my daily business I rarely use floats (just for text floating) because I destroy the box model and the content flow if I use float for layout purposes. 

As far as I know, If I use floats for layout then the element is always repainted when rearranging elements instead of a reflow which is from a browsers perspective way cheaper.

But actually feel free to use what ever works best for u.

Thanks for your feedback, I appreciate it a lot.
Max
