### ISSUE TITLE
Responsive: true

### ISSUE THREAD

**Issue by TrySound** [meandmax/lory#14]
Auto computing slide width out of the box.

**Comment by meandmax** [comment]
Hey @TrySound,

thanks for the feature request!

I do not think that this is a good idea. I showed in my examples how to make slides responsive via css mediaqueries, and I really don`t like the approach to do everything in JavaScript just because I can.

I think this the job can and should be done only in CSS and not in JavaScript.

Thanks, Max!

**Comment by TrySound** [comment]
@meandmax I need fluid slider, but not fixed. Do you have idea how to make it?

**Comment by Cordazar** [comment]
@TrySound Lory has since been updated to work with responsive slides.

**Comment by TrySound** [comment]
Thanks, @Cordazar!

**Comment by SiamKreative** [comment]
@Cordazar Can you please point me to a working example with fluid slider? I'm struggling to get this working.

**Comment by Cordazar** [comment]
@SiamKreative Here it is used on a live-site http://www.expressen.se/geo/mats-larsson/tjejerna-som-surfar-mot-normerna--hittar-gladjen-pa-vagorna/

**Comment by SiamKreative** [comment]
*Thanks for getting back to me* :)

Because I was unable to find documentation about fluid sliders, I decided to look around for another library agnostic script and I found http://wd.dizaina.net/en/scripts/peppermint/. It honestly suits me better as there's no additional work required to get it working with fluid sliders.

Still, I will check out your example to see how easy it easy to implement.

**Comment by Cordazar** [comment]
@SiamKreative 

You can also check the official page, http://meandmax.github.io/lory, and the examples for fluid sliders: 
- Single element - Percentage width [infinite]
- Single element - Percentage width [rewind]
