### ISSUE TITLE
Any option to toggle automatic slide change?

### ISSUE THREAD

**Issue by barisunver** [meandmax/lory#3]
Hi. I couldn't see any auto-change option, have I missed it? If this feature's not implemented, are you planning to do it in the future?

**Comment by meandmax** [comment]
Hey @barisunver,

for now an interval option is not implemented, because I want to keep the slider as lean as possible and I thought something like an interval is not really often needed in this kind of sliders. 

I think mostly interval is used by classic image slideshows, however if there are enough people who really need this feature I would think about implementing it. 

Shouldn`t be too much effort anyways. Do you actually have a use case where you need exactly this feature?

cheers Max

**Comment by caiotarifa** [comment]
I'd appreciate this feature. :+1: 

For now, it can be done with a `setInterval`, no? Like this:

```javascript
setInterval(function () {
  lory(simple).next;
});
```

**Comment by meandmax** [comment]
Thanks @caiotarifa for the codepen and the instructions how it can be done for now.

I think I will implementiert this feature when Im back home in 10 days and will let you know.

@barisunver, for now you have to do it like @caiotarifa did it.

Thanks
Max

**Comment by caiotarifa** [comment]
Is there any resolution about his?

**Comment by JacobDB** [comment]
Did you end up baking this in to the core, or no?

**Comment by andreasvirkus** [comment]
Is it in the plans still?

**Comment by erperejildo** [comment]
+1 for this feature
