### ISSUE TITLE
Error when compiling with rollup babel

### ISSUE THREAD

**Issue by magicspon** [meandmax/lory#480]
Hello,

I'm trying to import lory.js with rollup babel but it's crashing in a number of places.

This is my task:
https://gist.github.com/magicspon/db9b427b778b54b122502a950970e057

The first error is as follows:
SyntaxError: Unexpected token (214:19) in /Users/stockley/websites/snapldn/node_modules/lory.js/src/lory.js

`options = {...defaults, ...opts};`

It looks like lory.js is not being transpiled.

Has anyone had any issues importing `lory`. (It works perfectly with `browserify`).

Thanks
Dave

**Comment by wesleyhf** [comment]
+1

**Comment by trajedy** [comment]
I'm having similar issues.

`Error: Couldn't find preset "stage-0" relative to directory "/project-dir/node_modules/lory.js"`

So I added babel-preset-stage-0 as a dev dependency. Now the error I'm getting is the following.

`Error: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information`

Abbreviated .babelrc

```
{
  "presets": [
    ["latest", {
      "es2015": {
        "modules": false
      }
    }]
  ],
  "plugins": [
    ["transform-react-jsx", { "pragma": "h" }],
    "transform-object-rest-spread",
    "external-helpers"
  ]
}

```

**Comment by Benjamin-Dobell** [comment]
Not using Babel here, just rollup, I get:

```
<PROJECT PATH...>/node_modules/lory.js/src/lory.js: Unexpected token (214:19) in <PROJECT PATH...>//node_modules/lory.js/src/lory.js
```

Will investigate and report back.

**Comment by Benjamin-Dobell** [comment]
Oh right, whoops. Looks like I *need* Babel, ES7 spread operators in use. Hrm.

**Comment by Benjamin-Dobell** [comment]
Okay, yeah `jsnext:main` is set incorrectly in `package.json`. `jsnext:main` does _not_ refer to ES6/ES7 code. It must be valid ES5 with the exception of module syntax. Looks like it's been renamed to `pkg.module` though:
https://github.com/rollup/rollup/wiki/pkg.module

**Comment by nstanard** [comment]
Will be taking a closer look at using lory with rollup as soon as I am able.

**Comment by mahish** [comment]
Im still getting this error:(

**Comment by mahish** [comment]
@nstanard So I investigated this issue.
#### Edits in lory.js package:
1. First step is to create a new property in `package.json` of lory.js package → `module` (as @Benjamin-Dobell already posted). For now, it has point to `./src/lory.js` since there is no es module bundle in `./dist`
2. the package should `.npmnignore` the `.babelrc` in the package. That's the reason why @deckchairlabs is getting the error of missing preset. Because babel is looking for it in the lory.js folder. (for sake of investigation of this issue I simply deleted it from `node_modules/lory.js/.babelrc`)
#### Edits in my project's files:
3. Install https://babeljs.io/docs/plugins/transform-object-rest-spread/ because of: https://github.com/meandmax/lory/blob/d5f66bdfb46fe5d79a0cf631db3d2d564ce3c056/src/lory.js#L238
4. Make sure to have installed rollup plugins: https://github.com/rollup/rollup-plugin-node-resolve, https://github.com/rollup/rollup-plugin-commonjs . So the result rollup plugin settings is:
```         
plugins: [
  rollupNodeResolve({
    // use "module" field for ES6 module if possible. Default: true.
    module: true,
  }),
  rollupBabel({
    // exclude: 'node_modules/**', // Notice, how I commented it out!
  }),
  rollupCommonjs(),
  rollupUglify(),
],
```
#### Another edits in lory.js package:
5. Eventually, I made it to succesfull compilation. However, I kept getting runtime error of missing definition of `global`: https://github.com/meandmax/lory/blob/d5f66bdfb46fe5d79a0cf631db3d2d564ce3c056/src/utils/detect-prefixes.js#L40 So I changed it to: 
````
const computedStyle = window.getComputedStyle(el) || global.getComputedStyle(el);
hasTranslate3d = !!computedStyle.getPropertyValue(transform);
````

After this, It has started to work. Uf:)

In general, I find the whole package overcomplicated (yarn, webpack, many other packages). From "minimalistic slider written in vanilla JavaScript" I dont expect to have jquery version and tons of (even dev) dependecies. 
So I decided to try to migrate the project from webpack to rollup (because you can export to es module with rollup, and it is much more "minimalistic" than webpack). Just for fun & to learn. Lets see if i can make it.

**Comment by Eugeno** [comment]
Had the same error. Thx to @mahish for decision! @nstanard, pay attention to this.

**Comment by bgreater** [comment]
So using the NPM version of lory I was able to get it compiled correctly with rollup. I'm using Babel and and the `rollup-plugin-commonjs` plugin. which allows me to import lory as a commonjs module. 

Example rollup settings
```
...
plugins: [
          rollupCommonjs(
            {
              include: [
                'node_modules/lory.js/**',
              ]
            }
          )
...
```

Example usage
```
import lory from 'lory.js';

document.addEventListener('DOMContentLoaded', function () {
  var multiSlides = document.querySelector('.js_slider');
  // Have to use lory.lory b/c the default export is an object.
  lory.lory(multiSlides, {
      slidesToScroll: 5
  });
});
```

**Comment by nstanard** [comment]
@mahish I am not the owner of this resource and I would not feel comfortable merging in anything without first talking to Max. I am simply a humble servant ;)

That being said.... I will take a look at the work you've done and see if it's worth incorporating into the project.
